WPEFRAMEWORK_OCAST_VERSION = 727a8cd9eed1719b06c817ae83371a216638135c
WPEFRAMEWORK_OCAST_SITE_METHOD = git
WPEFRAMEWORK_OCAST_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginOcast.git
WPEFRAMEWORK_OCAST_INSTALL_STAGING = YES
WPEFRAMEWORK_OCAST_DEPENDENCIES = wpeframework

WPEFRAMEWORK_OCAST_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_OCAST_VERSION}

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DEBUG),y)
WPEFRAMEWORK_OCAST_CONF_OPTS += -DCMAKE_CXX_FLAGS='-g -Og'
endif

$(eval $(cmake-package))
