################################################################################
#
# wpeframework-devtools
#
################################################################################
WPEFRAMEWORK_DEVTOOLS_VERSION = 7e1f5015be7921c005ebead84e4f351b566cce65
WPEFRAMEWORK_DEVTOOLS_SITE_METHOD = git
WPEFRAMEWORK_DEVTOOLS_SITE = https://github.com/WebPlatformForEmbedded/WPEFramworkTests
WPEFRAMEWORK_DEVTOOLS_INSTALL_STAGING = YES
WPEFRAMEWORK_DEVTOOLS_DEPENDENCIES = wpeframework

WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_DEVTOOLS_VERSION}
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DCMAKE_CXX_FLAGS='-g -Og'

WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_TESTCONSOLE=ON
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_TESTSERVER=ON

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_TEST_CYCLICINSPECTOR),y)
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_APPS=ON -DWPEFRAMEWORK_TEST_CYCLICINSPECTOR=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_TEST_LOADER),y)
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_APPS=ON -DWPEFRAMEWORK_TEST_LOADER=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_NETWORKTEST),y)
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_APPS=ON -DWPEFRAMEWORK_TEST_NETWORKTEST=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_TEST_RPCLINK),y)
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_RPCLINK=ON -DWPEFRAMEWORK_RPC=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_LINUX_ONEWIRE),y)
WPEFRAMEWORK_DEVTOOLS_CONF_OPTS += -DWPEFRAMEWORK_TEST_APPS=ON -DWPEFRAMEWORK_TEST_LINUX1W=ON
endif

$(eval $(cmake-package))
